POST http://localhost:3001/api/notes
Content-Type: application/json

{
  "content": "AMD122",
  "important": false
}

###
GET http://localhost:3001/api/notes


###
GET http://localhost:3001/api/notes/6860e09b477a5cc0ebf5231e


###
PUT http://localhost:3001/api/notes/6860e09b477a5cc0ebf5231e
Content-Type: application/json

{
  "content": "AMD122",
  "important": true
}


###
DELETE http://localhost:3001/api/notes/6860e09b477a5cc0ebf5231e